baseURL = "http://localhost:1313/"
title = "ニコ技深セン / Nico-Tech Shenzhen website"
theme = "PaperMod"
disableKinds = ["RSS"]
[permalinks]
  archive  = "/archive/:year/:month/:slug/"
  teardown = "/teardown/:year/:month/:slug/"
  shenzhen = "/shenzhen/:year/:month/:slug/"
  fabcross = "/fabcross/:year/:month/:slug/"
[menu]
  [[menu.main]]
    name = "Teardown"
    url = "/teardown/"
    weight = 10
  [[menu.main]]
    name = "Shenzhen"
    url = "/shenzhen/"
    weight = 20
  [[menu.main]]
    name = "Fabcross"
    url = "/fabcross/"
    weight = 30
  [[menu.main]]
    name = "Archive"
    url = "/archive/"
    weight = 40

